services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn application:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
